USE Campus_Eats_Fall2020;

CREATE TABLE IF NOT EXISTS `Campus_Eats_Fall2020`.`item` (
  `item_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price_per_unit` FLOAT NULL DEFAULT 0.0,
  PRIMARY KEY (`item_id`, `restaurant_id`),
  CONSTRAINT `restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `Campus_Eats_Fall2020`.`restaurant` (`restaurant_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

LOCK TABLES `item` WRITE;

insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 1, 'nonummy maecenas tincidunt lacus', 9.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 2, 'sed accumsan', 5.87);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 3, 'ligula nec sem duis', 2.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 4, 'pretium', 10.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 5, 'in quis justo maecenas', 8.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 6, 'at feugiat non pretium', 8.68);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 7, 'posuere cubilia curae', 13.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 8, 'parturient montes', 12.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 9, 'pulvinar nulla pede ullamcorper', 10.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 10, 'purus phasellus in', 8.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 11, 'in', 14.1);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 12, 'orci mauris', 14.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 13, 'nascetur ridiculus', 5.95);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 14, 'ante nulla', 12.29);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 15, 'purus sit amet nulla', 11.36);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 16, 'velit eu est congue', 9.04);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 17, 'in sapien', 10.95);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 18, 'ut rhoncus', 7.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 19, 'ante vel ipsum', 12.51);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 20, 'ipsum primis', 11.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 21, 'enim', 8.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 22, 'dis parturient montes nascetur', 8.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 23, 'lacus purus aliquet at', 5.96);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 24, 'lacinia eget tincidunt', 2.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 25, 'molestie hendrerit at', 4.25);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 26, 'eu sapien cursus vestibulum', 4.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 27, 'posuere felis sed lacus', 3.39);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 28, 'eget tincidunt', 14.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 29, 'sit amet', 8.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 30, 'in faucibus orci', 12.05);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 31, 'pretium iaculis diam erat', 3.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 32, 'erat eros', 14.84);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 33, 'amet justo morbi ut', 8.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 34, 'magnis', 11.15);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 35, 'ligula suspendisse ornare', 4.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 36, 'pede', 8.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 37, 'in', 9.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 38, 'non ligula pellentesque ultrices', 8.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 39, 'lorem', 5.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 40, 'dapibus dolor vel', 3.49);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 41, 'felis donec semper sapien', 7.4);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 42, 'sociis natoque penatibus et', 9.47);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 43, 'vestibulum sed magna at', 10.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 44, 'eu', 7.69);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 45, 'ipsum primis in faucibus', 8.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 46, 'ridiculus', 11.63);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 47, 'eu felis', 3.49);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 48, 'aliquet at', 7.55);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 49, 'tortor id nulla ultrices', 8.39);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 50, 'etiam', 11.46);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 51, 'potenti nullam porttitor', 13.48);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 52, 'eleifend', 5.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 53, 'pede ullamcorper augue', 11.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 54, 'pede ullamcorper augue', 12.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 55, 'sit', 12.21);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 56, 'morbi', 9.56);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 57, 'id', 5.47);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 58, 'viverra', 6.37);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 59, 'montes', 7.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 60, 'lobortis', 2.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 61, 'sapien', 2.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 62, 'adipiscing', 14.67);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 63, 'feugiat et eros vestibulum', 8.51);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 64, 'sapien', 7.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 65, 'ut', 5.35);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 66, 'orci nullam', 5.03);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 67, 'dolor sit amet', 5.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 68, 'pede malesuada in', 12.66);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 69, 'nisl', 14.05);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 70, 'in leo maecenas pulvinar', 13.39);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 71, 'iaculis congue', 6.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 72, 'nulla suscipit ligula in', 12.01);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 73, 'sed lacus morbi', 10.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 74, 'at lorem integer', 2.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 75, 'massa', 8.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 76, 'viverra', 12.99);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 77, 'nisi nam ultrices libero', 10.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 78, 'pretium quis', 11.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 79, 'vitae', 8.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 80, 'volutpat convallis morbi odio', 2.85);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 81, 'cursus id turpis', 4.62);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 82, 'sodales', 11.25);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 83, 'amet cursus id', 5.88);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 84, 'felis sed', 4.63);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 85, 'pulvinar nulla pede', 2.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 86, 'vel sem sed', 14.19);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 87, 'vulputate vitae', 9.06);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 88, 'convallis duis consequat dui', 6.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 89, 'a', 9.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 90, 'mauris enim leo', 7.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 91, 'orci', 4.94);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 92, 'massa tempor', 6.47);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 93, 'ante ipsum primis', 3.15);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 94, 'semper porta volutpat quam', 12.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 95, 'nec', 5.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 96, 'ac nulla sed vel', 3.05);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 97, 'pulvinar sed nisl', 8.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 98, 'sem mauris laoreet', 4.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 99, 'amet', 14.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (1, 100, 'vitae mattis nibh ligula', 7.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 1, 'in libero ut', 3.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 2, 'convallis duis', 11.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 3, 'placerat praesent', 10.61);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 4, 'augue vel accumsan tellus', 14.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 5, 'cursus', 4.89);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 6, 'suscipit a', 3.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 7, 'proin leo odio porttitor', 5.98);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 8, 'pellentesque viverra', 6.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 9, 'eros', 14.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 10, 'diam cras', 9.2);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 11, 'accumsan', 12.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 12, 'nulla tellus in', 10.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 13, 'neque sapien placerat', 5.84);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 14, 'congue vivamus', 13.94);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 15, 'at', 10.85);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 16, 'id justo sit', 3.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 17, 'erat', 11.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 18, 'tristique', 14.35);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 19, 'nisl venenatis lacinia', 11.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 20, 'nibh fusce lacus purus', 13.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 21, 'lorem ipsum dolor sit', 14.54);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 22, 'at vulputate vitae', 5.11);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 23, 'id ligula suspendisse ornare', 11.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 24, 'ipsum primis in faucibus', 11.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 25, 'consequat nulla nisl nunc', 9.61);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 26, 'in lectus pellentesque', 5.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 27, 'cursus vestibulum', 8.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 28, 'faucibus cursus urna ut', 6.85);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 29, 'nonummy integer non velit', 10.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 30, 'ullamcorper purus', 4.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 31, 'lorem', 2.54);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 32, 'urna', 2.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 33, 'sapien', 8.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 34, 'pretium', 7.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 35, 'ultrices', 4.05);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 36, 'felis', 4.85);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 37, 'volutpat erat quisque erat', 13.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 38, 'vestibulum proin eu mi', 7.29);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 39, 'mauris lacinia sapien', 6.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 40, 'primis in faucibus', 8.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 41, 'in tempus sit', 13.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 42, 'quisque arcu', 13.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 43, 'est', 6.5);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 44, 'eleifend quam a', 3.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 45, 'accumsan odio curabitur convallis', 10.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 46, 'pede', 11.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 47, 'nibh fusce lacus', 3.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 48, 'praesent lectus vestibulum quam', 3.38);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 49, 'in est risus auctor', 2.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 50, 'eleifend', 4.87);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 51, 'nulla', 10.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 52, 'odio', 12.5);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 53, 'sit amet', 10.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 54, 'pretium quis lectus suspendisse', 6.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 55, 'nulla suspendisse', 5.62);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 56, 'justo sit amet', 2.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 57, 'donec vitae', 4.89);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 58, 'leo odio porttitor id', 2.19);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 59, 'dolor sit amet', 3.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 60, 'massa quis', 2.67);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 61, 'nisl', 4.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 62, 'in magna bibendum', 3.51);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 63, 'orci luctus et', 9.21);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 64, 'eros viverra', 7.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 65, 'lacus curabitur at ipsum', 11.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 66, 'vitae', 12.06);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 67, 'in', 5.26);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 68, 'amet', 13.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 69, 'amet', 5.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 70, 'mi nulla ac enim', 3.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 71, 'morbi ut odio cras', 13.15);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 72, 'at turpis', 4.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 73, 'sapien iaculis congue vivamus', 13.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 74, 'ac', 7.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 75, 'elementum', 5.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 76, 'ligula', 2.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 77, 'molestie nibh in', 2.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 78, 'in congue etiam justo', 2.21);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 79, 'luctus et ultrices posuere', 6.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 80, 'posuere cubilia curae mauris', 3.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 81, 'amet nunc viverra dapibus', 6.57);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 82, 'accumsan odio curabitur', 12.29);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 83, 'diam neque vestibulum eget', 6.39);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 84, 'turpis donec posuere', 11.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 85, 'dolor', 9.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 86, 'at', 13.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 87, 'mi integer ac neque', 5.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 88, 'nisl aenean lectus pellentesque', 10.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 89, 'in felis donec', 13.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 90, 'pede justo eu', 2.99);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 91, 'luctus et ultrices posuere', 8.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 92, 'amet consectetuer', 3.71);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 93, 'ultrices', 12.63);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 94, 'sapien', 4.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 95, 'condimentum neque sapien', 13.37);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 96, 'lacus morbi', 8.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 97, 'pellentesque viverra', 2.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 98, 'viverra', 2.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 99, 'augue', 6.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (2, 100, 'sed vestibulum sit', 6.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 1, 'orci nullam', 9.73);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 2, 'mollis molestie lorem', 12.99);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 3, 'nulla elit ac', 10.07);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 4, 'nec', 11.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 5, 'vivamus metus', 4.56);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 6, 'eu', 13.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 7, 'eget vulputate ut ultrices', 9.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 8, 'fusce congue diam id', 9.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 9, 'cubilia curae duis', 12.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 10, 'et ultrices posuere', 14.29);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 11, 'arcu libero rutrum ac', 12.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 12, 'pede justo', 7.05);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 13, 'ligula pellentesque ultrices', 6.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 14, 'felis', 6.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 15, 'mattis egestas metus aenean', 5.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 16, 'rhoncus', 6.47);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 17, 'praesent lectus vestibulum', 7.52);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 18, 'ultrices phasellus', 10.22);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 19, 'montes nascetur ridiculus mus', 5.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 20, 'massa id nisl venenatis', 7.36);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 21, 'et eros', 13.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 22, 'nunc nisl duis', 11.07);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 23, 'vestibulum ante ipsum', 11.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 24, 'magna', 9.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 25, 'molestie nibh', 12.55);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 26, 'et ultrices posuere', 2.36);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 27, 'integer', 6.07);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 28, 'ut', 11.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 29, 'lobortis vel dapibus at', 6.46);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 30, 'in magna bibendum', 12.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 31, 'odio', 12.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 32, 'fermentum', 2.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 33, 'arcu', 3.51);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 34, 'ut', 5.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 35, 'fusce', 13.52);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 36, 'nibh in hac', 9.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 37, 'eget elit', 8.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 38, 'nibh', 10.05);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 39, 'cubilia curae donec pharetra', 12.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 40, 'amet', 11.83);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 41, 'parturient montes nascetur ridiculus', 3.3);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 42, 'donec semper sapien a', 5.07);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 43, 'condimentum neque sapien placerat', 11.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 44, 'id massa', 3.15);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 45, 'non quam nec dui', 3.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 46, 'congue vivamus metus arcu', 12.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 47, 'sed augue aliquam', 3.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 48, 'eu magna vulputate', 10.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 49, 'elit sodales scelerisque mauris', 12.1);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 50, 'duis faucibus accumsan odio', 14.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 51, 'pulvinar sed', 12.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 52, 'vel accumsan', 8.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 53, 'at nulla suspendisse potenti', 13.06);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 54, 'quisque erat eros', 5.15);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 55, 'at velit', 12.63);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 56, 'platea dictumst maecenas ut', 14.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 57, 'nunc nisl', 12.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 58, 'eget rutrum at', 9.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 59, 'convallis morbi odio', 3.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 60, 'augue aliquam erat', 14.48);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 61, 'tempor convallis nulla', 14.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 62, 'neque', 4.69);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 63, 'mattis odio', 9.11);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 64, 'ultrices', 11.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 65, 'justo', 9.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 66, 'viverra', 4.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 67, 'hac habitasse', 7.3);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 68, 'vulputate', 12.89);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 69, 'at ipsum ac tellus', 11.0);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 70, 'phasellus sit amet erat', 14.85);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 71, 'id', 13.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 72, 'aliquet at feugiat', 3.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 73, 'velit', 10.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 74, 'amet justo', 9.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 75, 'at', 4.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 76, 'sodales scelerisque mauris sit', 8.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 77, 'pharetra magna vestibulum aliquet', 12.01);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 78, 'pretium iaculis justo', 11.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 79, 'est lacinia nisi venenatis', 6.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 80, 'vitae nisl aenean', 6.0);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 81, 'tortor eu', 2.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 82, 'vehicula', 8.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 83, 'gravida sem praesent', 11.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 84, 'eget', 5.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 85, 'dolor quis odio consequat', 11.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 86, 'lorem id ligula suspendisse', 13.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 87, 'purus sit amet nulla', 10.2);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 88, 'morbi vel lectus in', 6.54);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 89, 'et', 14.4);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 90, 'lectus pellentesque at nulla', 13.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 91, 'eu est', 2.38);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 92, 'ac', 2.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 93, 'tristique est', 3.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 94, 'in hac', 10.04);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 95, 'aliquet maecenas leo odio', 8.69);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 96, 'dolor quis odio', 10.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 97, 'odio in', 2.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 98, 'nisl nunc nisl duis', 5.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 99, 'lorem integer', 8.94);
insert into item (item_id, restaurant_id, name, price_per_unit) values (3, 100, 'vestibulum aliquet ultrices erat', 6.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 1, 'et magnis dis', 14.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 2, 'pretium iaculis', 14.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 3, 'morbi quis tortor', 6.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 4, 'ridiculus mus vivamus vestibulum', 9.44);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 5, 'imperdiet sapien urna pretium', 7.44);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 6, 'sed', 4.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 7, 'tellus', 4.24);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 8, 'tempor convallis nulla neque', 10.95);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 9, 'orci eget orci', 2.35);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 10, 'mollis molestie lorem quisque', 14.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 11, 'diam', 11.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 12, 'maecenas pulvinar', 8.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 13, 'eget', 14.21);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 14, 'aliquam lacus', 10.4);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 15, 'sed interdum', 2.96);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 16, 'consectetuer adipiscing elit', 9.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 17, 'sollicitudin ut suscipit', 9.81);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 18, 'vitae', 3.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 19, 'rhoncus aliquam lacus morbi', 14.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 20, 'pellentesque ultrices mattis odio', 6.62);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 21, 'vestibulum vestibulum ante ipsum', 3.89);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 22, 'pede', 12.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 23, 'dui maecenas', 5.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 24, 'suspendisse ornare consequat', 4.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 25, 'morbi', 9.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 26, 'a feugiat', 2.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 27, 'erat tortor', 12.55);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 28, 'lacinia erat vestibulum sed', 9.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 29, 'rutrum neque aenean', 2.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 30, 'duis', 7.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 31, 'ultrices', 4.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 32, 'pede ullamcorper augue a', 12.23);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 33, 'nascetur ridiculus mus', 3.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 34, 'tellus', 11.56);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 35, 'in ante vestibulum', 6.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 36, 'vivamus tortor', 7.52);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 37, 'nisl', 8.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 38, 'primis in', 2.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 39, 'ipsum primis in', 13.57);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 40, 'nulla integer', 6.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 41, 'lobortis', 2.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 42, 'sodales scelerisque mauris', 4.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 43, 'congue', 9.01);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 44, 'orci luctus et ultrices', 8.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 45, 'nullam sit amet turpis', 13.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 46, 'mus', 12.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 47, 'a ipsum', 11.89);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 48, 'ligula nec sem', 7.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 49, 'ultrices posuere cubilia curae', 10.67);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 50, 'praesent id massa', 9.37);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 51, 'pede libero quis', 12.83);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 52, 'vitae quam suspendisse potenti', 6.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 53, 'in porttitor', 5.52);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 54, 'pretium iaculis diam erat', 5.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 55, 'volutpat eleifend donec ut', 13.0);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 56, 'eleifend pede', 7.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 57, 'magna at', 12.4);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 58, 'congue vivamus metus', 8.81);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 59, 'lobortis vel dapibus at', 5.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 60, 'interdum mauris ullamcorper', 9.84);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 61, 'fusce', 7.52);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 62, 'turpis elementum ligula', 3.19);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 63, 'at nulla suspendisse potenti', 3.1);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 64, 'aliquam', 7.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 65, 'ut dolor morbi vel', 11.68);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 66, 'dolor', 5.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 67, 'varius ut blandit non', 4.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 68, 'amet', 10.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 69, 'elementum eu interdum eu', 14.57);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 70, 'eu orci', 7.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 71, 'in', 11.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 72, 'in', 14.68);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 73, 'phasellus id sapien', 3.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 74, 'ac neque duis bibendum', 3.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 75, 'turpis adipiscing lorem', 4.39);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 76, 'vestibulum', 10.91);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 77, 'nulla pede ullamcorper augue', 2.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 78, 'nec condimentum neque', 7.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 79, 'pede', 12.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 80, 'convallis nunc', 4.37);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 81, 'vitae consectetuer', 14.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 82, 'nec condimentum neque sapien', 9.95);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 83, 'dolor sit', 7.67);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 84, 'proin', 7.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 85, 'turpis elementum ligula vehicula', 14.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 86, 'massa', 7.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 87, 'ut', 2.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 88, 'lectus suspendisse potenti in', 9.3);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 89, 'aenean fermentum donec ut', 3.53);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 90, 'sed accumsan felis ut', 11.62);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 91, 'pharetra magna vestibulum aliquet', 10.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 92, 'nisl venenatis', 12.96);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 93, 'massa tempor convallis', 2.41);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 94, 'eu felis fusce', 3.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 95, 'quam pede lobortis ligula', 10.94);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 96, 'nisl ut volutpat sapien', 7.1);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 97, 'hac habitasse platea dictumst', 11.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 98, 'at nulla suspendisse', 10.84);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 99, 'quis libero', 8.36);
insert into item (item_id, restaurant_id, name, price_per_unit) values (4, 100, 'lacus at', 13.88);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 1, 'neque aenean auctor', 4.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 2, 'platea dictumst maecenas ut', 4.54);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 3, 'eget', 6.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 4, 'dapibus dolor vel est', 9.48);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 5, 'vestibulum rutrum', 4.86);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 6, 'curae donec', 2.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 7, 'nibh', 7.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 8, 'nam ultrices libero', 14.01);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 9, 'felis', 7.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 10, 'potenti cras', 3.26);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 11, 'morbi porttitor lorem', 8.21);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 12, 'ut tellus nulla ut', 10.83);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 13, 'congue eget', 4.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 14, 'ipsum', 11.96);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 15, 'volutpat convallis morbi odio', 4.12);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 16, 'vivamus metus arcu adipiscing', 11.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 17, 'eu orci mauris', 2.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 18, 'sit amet', 7.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 19, 'nam dui', 11.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 20, 'quis tortor id', 5.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 21, 'tincidunt ante vel', 9.69);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 22, 'accumsan', 2.29);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 23, 'in purus eu magna', 2.39);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 24, 'posuere', 12.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 25, 'egestas metus aenean', 12.91);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 26, 'eu', 2.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 27, 'duis bibendum felis', 14.88);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 28, 'sollicitudin mi sit', 14.07);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 29, 'turpis eget elit', 14.68);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 30, 'luctus nec molestie sed', 10.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 31, 'vivamus metus', 6.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 32, 'et commodo vulputate justo', 3.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 33, 'faucibus cursus', 5.81);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 34, 'quis augue', 2.54);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 35, 'risus praesent lectus vestibulum', 6.57);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 36, 'congue risus', 6.06);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 37, 'vivamus vel nulla eget', 5.83);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 38, 'accumsan tortor quis turpis', 7.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 39, 'sed lacus morbi', 6.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 40, 'id nulla', 7.95);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 41, 'posuere nonummy', 6.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 42, 'tempor turpis nec', 12.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 43, 'a', 8.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 44, 'iaculis congue', 14.03);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 45, 'vehicula condimentum curabitur in', 3.04);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 46, 'non', 14.66);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 47, 'eu', 14.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 48, 'nonummy', 10.29);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 49, 'velit', 12.24);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 50, 'nascetur ridiculus mus', 6.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 51, 'sit amet justo morbi', 7.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 52, 'turpis', 9.35);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 53, 'placerat', 14.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 54, 'lacinia', 5.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 55, 'purus eu magna vulputate', 14.54);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 56, 'mi', 3.0);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 57, 'et commodo vulputate justo', 7.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 58, 'quam turpis adipiscing', 9.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 59, 'pede ac', 13.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 60, 'viverra', 14.07);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 61, 'ligula nec', 2.75);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 62, 'gravida', 8.51);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 63, 'enim in tempor', 3.63);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 64, 'ultrices enim lorem', 8.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 65, 'id massa', 13.65);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 66, 'vitae quam', 11.73);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 67, 'vel pede morbi porttitor', 4.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 68, 'cum', 2.22);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 69, 'orci pede', 4.67);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 70, 'sit amet', 2.66);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 71, 'quam', 14.17);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 72, 'in purus eu magna', 8.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 73, 'ultrices phasellus id sapien', 8.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 74, 'phasellus id sapien', 14.09);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 75, 'sapien dignissim vestibulum', 14.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 76, 'pellentesque', 2.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 77, 'eget tincidunt eget tempus', 2.06);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 78, 'fusce', 11.73);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 79, 'dui vel', 7.38);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 80, 'nulla', 12.91);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 81, 'ligula suspendisse ornare', 11.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 82, 'consequat', 3.04);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 83, 'ac', 5.38);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 84, 'non interdum', 13.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 85, 'massa id nisl venenatis', 10.23);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 86, 'lectus pellentesque', 5.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 87, 'suscipit ligula in', 2.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 88, 'sem sed sagittis nam', 5.81);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 89, 'in libero ut', 10.73);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 90, 'at turpis donec posuere', 13.55);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 91, 'donec posuere metus', 10.51);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 92, 'posuere nonummy integer non', 14.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 93, 'luctus cum sociis', 3.48);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 94, 'sapien urna', 3.38);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 95, 'mauris sit amet', 11.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 96, 'posuere cubilia curae nulla', 14.82);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 97, 'luctus tincidunt', 4.2);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 98, 'aenean', 8.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 99, 'nulla mollis molestie lorem', 2.49);
insert into item (item_id, restaurant_id, name, price_per_unit) values (5, 100, 'risus praesent lectus', 5.46);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 1, 'vivamus vestibulum sagittis sapien', 9.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 2, 'blandit', 6.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 3, 'cras in purus eu', 9.46);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 4, 'semper', 9.88);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 5, 'in lectus pellentesque at', 5.61);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 6, 'erat eros viverra', 10.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 7, 'aenean auctor gravida sem', 8.22);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 8, 'pellentesque', 10.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 9, 'primis in faucibus orci', 10.69);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 10, 'amet', 7.27);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 11, 'felis sed lacus morbi', 14.47);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 12, 'velit id pretium iaculis', 13.19);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 13, 'nulla nunc', 14.18);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 14, 'leo rhoncus sed vestibulum', 7.78);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 15, 'nibh in hac', 12.6);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 16, 'nec nisi vulputate', 4.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 17, 'tellus semper interdum', 9.33);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 18, 'neque vestibulum eget vulputate', 8.68);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 19, 'sem duis aliquam convallis', 12.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 20, 'felis ut', 11.69);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 21, 'venenatis non', 7.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 22, 'sem mauris', 14.48);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 23, 'nisi eu orci', 2.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 24, 'suspendisse potenti nullam', 4.87);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 25, 'malesuada in imperdiet et', 3.93);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 26, 'id luctus nec molestie', 4.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 27, 'odio justo', 7.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 28, 'vehicula', 10.66);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 29, 'vitae nisl aenean', 14.21);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 30, 'quis', 12.3);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 31, 'massa id lobortis', 6.24);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 32, 'malesuada', 3.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 33, 'sit', 6.46);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 34, 'auctor gravida sem praesent', 3.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 35, 'posuere felis sed lacus', 4.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 36, 'turpis sed ante vivamus', 12.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 37, 'sit amet sapien', 9.03);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 38, 'amet diam', 9.43);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 39, 'sed ante', 10.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 40, 'potenti in', 6.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 41, 'faucibus', 2.04);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 42, 'arcu adipiscing', 8.2);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 43, 'duis bibendum morbi non', 7.72);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 44, 'ac diam cras pellentesque', 6.37);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 45, 'odio porttitor id', 6.1);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 46, 'donec dapibus', 13.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 47, 'sit amet', 11.02);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 48, 'vestibulum sed magna at', 12.91);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 49, 'venenatis lacinia aenean', 3.23);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 50, 'sodales scelerisque', 4.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 51, 'cursus id turpis integer', 12.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 52, 'at velit eu est', 14.45);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 53, 'vestibulum proin eu mi', 6.92);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 54, 'orci luctus et', 10.08);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 55, 'nam ultrices libero', 4.38);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 56, 'eget orci', 13.1);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 57, 'semper rutrum', 2.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 58, 'lorem', 14.55);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 59, 'leo odio', 9.74);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 60, 'luctus et ultrices', 3.46);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 61, 'vivamus', 6.34);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 62, 'varius', 9.19);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 63, 'nec', 5.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 64, 'libero nullam', 13.91);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 65, 'lacinia aenean sit', 7.77);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 66, 'massa id', 7.58);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 67, 'sit amet justo', 5.64);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 68, 'amet consectetuer adipiscing', 4.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 69, 'sodales sed', 2.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 70, 'cursus urna ut tellus', 13.42);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 71, 'odio porttitor', 3.28);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 72, 'nullam varius', 14.32);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 73, 'posuere metus vitae', 2.16);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 74, 'vivamus metus', 5.3);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 75, 'rhoncus aliquet', 3.7);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 76, 'volutpat', 8.57);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 77, 'nam', 9.11);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 78, 'justo nec condimentum neque', 11.52);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 79, 'rhoncus mauris enim leo', 7.31);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 80, 'quisque id justo', 13.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 81, 'praesent id', 2.8);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 82, 'vitae mattis', 3.63);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 83, 'lorem ipsum dolor sit', 12.4);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 84, 'sed ante vivamus tortor', 2.26);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 85, 'eu', 4.44);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 86, 'ante vivamus', 13.04);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 87, 'aliquet', 10.14);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 88, 'dui vel sem', 12.79);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 89, 'risus praesent lectus', 11.9);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 90, 'quam', 2.13);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 91, 'in congue', 6.03);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 92, 'id ligula suspendisse', 9.01);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 93, 'lacinia nisi venenatis', 6.15);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 94, 'consequat', 8.48);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 95, 'mattis egestas metus', 7.97);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 96, 'eget rutrum', 11.85);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 97, 'cursus vestibulum proin eu', 13.59);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 98, 'dui proin leo', 2.2);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 99, 'justo sit amet sapien', 6.76);
insert into item (item_id, restaurant_id, name, price_per_unit) values (6, 100, 'nibh in', 10.06);

UNLOCK TABLES;